-- Accounting & Finance foundation.
--
-- Five primary objects:
--   * chart_of_accounts      — hierarchical, per-tenant CoA
--   * accounting_periods     — monthly periods plus a 13th adjustment period
--   * journal_entries        — header row, one per balanced double-entry
--   * journal_lines          — debit / credit lines, sum-balanced per entry
--   * posting_rules          — event-to-accounts mapping for the auto-poster
--
-- Plus a `schema_migrations` table (lives in db/pool.go), and a per-tenant
-- sequence for journal entry numbering.

-- ─────────── Enums ───────────

CREATE TYPE account_class AS ENUM (
    'asset', 'liability', 'equity', 'income', 'expense'
);

CREATE TYPE account_normal_balance AS ENUM ('debit', 'credit');

CREATE TYPE journal_entry_status AS ENUM (
    'draft',            -- manual entry, being edited
    'pending_approval', -- manual entry, checker hasn't acted yet
    'posted',           -- final, immutable
    'rejected'          -- checker rejected
);

CREATE TYPE journal_entry_type AS ENUM (
    'auto',             -- generated by the posting engine
    'manual',           -- created by a finance user
    'adjustment',       -- year-end / period-end accrual
    'reversal',         -- reverses a prior entry
    'opening_balance'   -- migration / go-live entry
);

CREATE TYPE accounting_period_status AS ENUM ('open', 'closed');

-- ─────────── Chart of Accounts ───────────

CREATE TABLE chart_of_accounts (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    code              text NOT NULL,
    name              text NOT NULL,
    class             account_class NOT NULL,
    -- Account "type" is a free-text refinement within the class
    -- (e.g. 'current_asset', 'fixed_asset', 'member_savings'). Kept
    -- flexible so tenants can introduce categories without enum
    -- migrations.
    type              text NOT NULL,
    parent_id         uuid REFERENCES chart_of_accounts(id) ON DELETE SET NULL,
    normal_balance    account_normal_balance NOT NULL,
    currency_code     char(3) NOT NULL DEFAULT 'KES',
    is_active         boolean NOT NULL DEFAULT true,
    is_system_locked  boolean NOT NULL DEFAULT false,
    description       text,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, code)
);
CREATE INDEX chart_of_accounts_parent_idx ON chart_of_accounts (tenant_id, parent_id);
CREATE INDEX chart_of_accounts_class_idx  ON chart_of_accounts (tenant_id, class, is_active);
ALTER TABLE chart_of_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE chart_of_accounts FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_coa ON chart_of_accounts
    USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE ON chart_of_accounts TO nexus_app;

-- ─────────── Accounting periods ───────────

CREATE TABLE accounting_periods (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    year         integer NOT NULL,
    month        integer NOT NULL CHECK (month BETWEEN 1 AND 13),
    status       accounting_period_status NOT NULL DEFAULT 'open',
    opened_at    timestamptz,
    opened_by    uuid,
    closed_at    timestamptz,
    closed_by    uuid,
    notes        text,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, year, month)
);
ALTER TABLE accounting_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE accounting_periods FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_periods ON accounting_periods
    USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE ON accounting_periods TO nexus_app;

-- ─────────── Journal entries (header) ───────────
--
-- entry_no is a per-tenant sequential number generated at post time.
-- Drafts and pending entries don't have one yet — they get JE-XXXX
-- only when status flips to 'posted'.

CREATE TABLE journal_entries (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    entry_no          text,
    entry_date        date NOT NULL,
    value_date        date NOT NULL,
    period_year       integer NOT NULL,
    period_month      integer NOT NULL CHECK (period_month BETWEEN 1 AND 13),
    entry_type        journal_entry_type NOT NULL DEFAULT 'manual',
    source_module     text,
    source_ref        text,
    narration         text NOT NULL,
    status            journal_entry_status NOT NULL DEFAULT 'draft',
    total_debits      numeric(18,2) NOT NULL DEFAULT 0 CHECK (total_debits >= 0),
    total_credits     numeric(18,2) NOT NULL DEFAULT 0 CHECK (total_credits >= 0),
    reversal_of       uuid REFERENCES journal_entries(id) ON DELETE SET NULL,
    -- Maker / checker. created_by for the maker; posted_by for the
    -- checker (or system, when auto-posted).
    created_by        uuid,
    created_at        timestamptz NOT NULL DEFAULT now(),
    posted_by         uuid,
    posted_at         timestamptz,
    rejected_by       uuid,
    rejected_at       timestamptz,
    rejection_reason  text,
    updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX journal_entries_period_idx
    ON journal_entries (tenant_id, period_year, period_month, status);
CREATE INDEX journal_entries_source_idx
    ON journal_entries (tenant_id, source_module, source_ref);
CREATE INDEX journal_entries_date_idx
    ON journal_entries (tenant_id, entry_date DESC);
CREATE UNIQUE INDEX journal_entries_entry_no_idx
    ON journal_entries (tenant_id, entry_no) WHERE entry_no IS NOT NULL;
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_entries FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_journal_entries ON journal_entries
    USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE ON journal_entries TO nexus_app;

-- ─────────── Journal lines (debit / credit detail) ───────────
--
-- Per-line CHECK enforces that exactly one of debit/credit is positive
-- (the other is zero). The header-level balance check lives in
-- application code — Postgres can't enforce SUM(debit)=SUM(credit)
-- declaratively across rows.

CREATE TABLE journal_lines (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    entry_id    uuid NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
    line_no     integer NOT NULL,
    account_id  uuid NOT NULL REFERENCES chart_of_accounts(id) ON DELETE RESTRICT,
    debit       numeric(18,2) NOT NULL DEFAULT 0 CHECK (debit >= 0),
    credit      numeric(18,2) NOT NULL DEFAULT 0 CHECK (credit >= 0),
    narration   text,
    UNIQUE (entry_id, line_no),
    CHECK ((debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0))
);
CREATE INDEX journal_lines_account_idx ON journal_lines (tenant_id, account_id);
CREATE INDEX journal_lines_entry_idx   ON journal_lines (entry_id);
ALTER TABLE journal_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_journal_lines ON journal_lines
    USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT ON journal_lines TO nexus_app;

-- ─────────── Posting rules (auto-posting engine config) ───────────

CREATE TABLE posting_rules (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    event_code  text NOT NULL,
    -- product_id is the loan/savings/share product the rule applies to,
    -- if any. NULL = global rule for the event.
    product_id  uuid,
    name        text NOT NULL,
    description text,
    -- lines is the rule template as JSONB:
    -- [{"side":"debit","account_code":"1000","amount":"amount"}, ...]
    -- "amount" is a tag the caller fills in at post time.
    lines       jsonb NOT NULL,
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, event_code, product_id)
);
ALTER TABLE posting_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE posting_rules FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_posting_rules ON posting_rules
    USING (tenant_id = current_tenant_id())
    WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE ON posting_rules TO nexus_app;

-- ─────────── Default Chart of Accounts seed ───────────
--
-- Standard SACCO accounts mapped to SASRA reporting categories.
-- All system-locked so the foundation stays intact — tenants can add
-- their own accounts on top.

INSERT INTO chart_of_accounts (tenant_id, code, name, class, type, normal_balance, is_system_locked, description)
SELECT t.id, c.code, c.name, c.class::account_class, c.type, c.nb::account_normal_balance, true, c.descr
FROM tenants t CROSS JOIN (VALUES
  -- ASSETS — Current
  ('1000', 'Cash on Hand',                       'asset',     'current_asset',      'debit',  'Vault + petty cash across branches'),
  ('1010', 'Cash at Till',                       'asset',     'current_asset',      'debit',  'Per-teller till balance'),
  ('1020', 'Bank Current Account',               'asset',     'current_asset',      'debit',  'Operating bank account'),
  ('1030', 'M-Pesa Float',                       'asset',     'current_asset',      'debit',  'Paybill float balance'),
  ('1040', 'Airtel Money Float',                 'asset',     'current_asset',      'debit',  'Airtel float balance'),
  ('1100', 'Member Loans Receivable',            'asset',     'current_asset',      'debit',  'Outstanding member loan principal'),
  ('1110', 'Loan Interest Receivable',           'asset',     'current_asset',      'debit',  'Accrued unpaid interest'),
  ('1120', 'Loan Loss Provision',                'asset',     'contra_asset',       'credit', 'Provisioning contra-asset'),
  ('1200', 'Other Receivables',                  'asset',     'current_asset',      'debit',  'Sundry debtors'),
  ('1210', 'Prepayments',                        'asset',     'current_asset',      'debit',  'Insurance, rent paid in advance'),
  -- ASSETS — Non-current
  ('1500', 'Furniture and Fittings',             'asset',     'fixed_asset',        'debit',  'Gross cost of office furniture'),
  ('1510', 'Office Equipment',                   'asset',     'fixed_asset',        'debit',  'Gross cost of office equipment'),
  ('1520', 'Computer Hardware',                  'asset',     'fixed_asset',        'debit',  'Gross cost of IT hardware'),
  ('1530', 'Motor Vehicles',                     'asset',     'fixed_asset',        'debit',  'Gross cost of motor vehicles'),
  ('1540', 'Buildings',                          'asset',     'fixed_asset',        'debit',  'Gross cost of buildings'),
  ('1550', 'Land',                               'asset',     'fixed_asset',        'debit',  'Land at cost (not depreciated)'),
  ('1590', 'Accumulated Depreciation',           'asset',     'contra_asset',       'credit', 'Contra-asset for fixed assets'),
  ('1600', 'Intangible Assets',                  'asset',     'fixed_asset',        'debit',  'Software licences, etc.'),
  ('1700', 'Long-Term Investments',              'asset',     'non_current_asset',  'debit',  'Strategic investments'),
  -- LIABILITIES — Current (member deposits + payables)
  ('2000', 'Ordinary Savings Deposits',          'liability', 'member_savings',     'credit', 'Standard member savings'),
  ('2010', 'Holiday Savings',                    'liability', 'member_savings',     'credit', 'Goal-based holiday savings'),
  ('2020', 'Emergency Savings',                  'liability', 'member_savings',     'credit', 'Emergency fund savings'),
  ('2030', 'Goal Savings',                       'liability', 'member_savings',     'credit', 'Other goal-tagged savings'),
  ('2040', 'Junior Savings',                     'liability', 'member_savings',     'credit', 'Children savings products'),
  ('2100', 'Fixed Deposits',                     'liability', 'member_deposits',    'credit', 'Term deposit liabilities'),
  ('2200', 'Withholding Tax Payable',            'liability', 'current_liability',  'credit', 'WHT collected pending KRA remittance'),
  ('2210', 'Accrued Expenses',                   'liability', 'current_liability',  'credit', 'Expenses incurred not yet paid'),
  ('2220', 'Dividend Payable',                   'liability', 'current_liability',  'credit', 'Declared dividends pending payment'),
  ('2230', 'Other Payables',                     'liability', 'current_liability',  'credit', 'Sundry creditors'),
  ('2240', 'Unearned Income',                    'liability', 'current_liability',  'credit', 'Fees collected in advance'),
  ('2250', 'Till / Vault Variance',              'liability', 'current_liability',  'credit', 'Cash differences pending resolution'),
  -- LIABILITIES — Non-current
  ('2500', 'Long-Term Borrowings',               'liability', 'long_term_liability','credit', 'Loans from banks / SACCOs'),
  ('2510', 'Institutional Loans',                'liability', 'long_term_liability','credit', 'External institutional financing'),
  -- EQUITY
  ('3000', 'Member Share Capital',               'equity',    'share_capital',      'credit', 'Member shareholdings at par value'),
  ('3010', 'Retained Earnings',                  'equity',    'retained_earnings',  'credit', 'Accumulated surplus carried forward'),
  ('3020', 'Statutory Reserve Fund',             'equity',    'reserve',            'credit', 'SASRA minimum 15% of net surplus'),
  ('3030', 'General Reserves',                   'equity',    'reserve',            'credit', 'Discretionary reserves'),
  ('3040', 'Revaluation Reserve',                'equity',    'reserve',            'credit', 'Asset revaluation surplus'),
  ('3050', 'Institutional Capital',              'equity',    'institutional',      'credit', 'Donated / institutional capital'),
  -- INCOME
  ('4000', 'Loan Interest Income',               'income',    'operating_income',   'credit', 'Interest earned on member loans'),
  ('4010', 'Loan Processing Fee Income',         'income',    'fee_income',         'credit', 'Loan origination fees'),
  ('4020', 'Loan Insurance / LPF Income',        'income',    'fee_income',         'credit', 'Loan protection premiums'),
  ('4030', 'Penalty Income',                     'income',    'fee_income',         'credit', 'Late payment penalties'),
  ('4040', 'Membership Fee Income',              'income',    'fee_income',         'credit', 'Annual membership fees'),
  ('4050', 'Account Maintenance Fee Income',     'income',    'fee_income',         'credit', 'Account upkeep fees'),
  ('4060', 'Dormancy Fee Income',                'income',    'fee_income',         'credit', 'Fees on dormant accounts'),
  ('4070', 'Withdrawal Penalty Income',          'income',    'fee_income',         'credit', 'Early withdrawal penalties'),
  ('4100', 'Investment Income',                  'income',    'investment_income',  'credit', 'Returns on SACCO investments'),
  ('4200', 'Write-Off Recovery Income',          'income',    'other_income',       'credit', 'Recoveries on previously written-off loans'),
  ('4300', 'Gain on Asset Disposal',             'income',    'other_income',       'credit', 'Profit on fixed-asset disposal'),
  ('4900', 'Other Income',                       'income',    'other_income',       'credit', 'Sundry income'),
  -- EXPENSES
  ('5000', 'Interest on Member Deposits',        'expense',   'finance_expense',    'debit',  'Interest paid to depositors'),
  ('5010', 'Dividend Expense',                   'expense',   'distribution',       'debit',  'Dividends declared to shareholders'),
  ('5100', 'Staff Salaries and Wages',           'expense',   'staff_cost',         'debit',  'Direct staff compensation'),
  ('5110', 'Staff Benefits',                     'expense',   'staff_cost',         'debit',  'Health insurance, allowances'),
  ('5120', 'Statutory Contributions',            'expense',   'staff_cost',         'debit',  'NSSF, NHIF, PAYE remittances'),
  ('5200', 'Depreciation Expense',               'expense',   'non_cash_expense',   'debit',  'Monthly depreciation of fixed assets'),
  ('5210', 'Loan Loss Provisioning Expense',     'expense',   'non_cash_expense',   'debit',  'Movement in provision balance'),
  ('5220', 'Loss on Asset Disposal',             'expense',   'non_cash_expense',   'debit',  'Loss on fixed-asset disposal'),
  ('5300', 'Rent and Utilities',                 'expense',   'admin_expense',      'debit',  'Office rent, electricity, water'),
  ('5310', 'Communications',                     'expense',   'admin_expense',      'debit',  'Telephone, internet, SMS, postage'),
  ('5320', 'Office Supplies',                    'expense',   'admin_expense',      'debit',  'Stationery, consumables'),
  ('5330', 'Travel and Subsistence',             'expense',   'admin_expense',      'debit',  'Business travel costs'),
  ('5340', 'Professional Fees',                  'expense',   'admin_expense',      'debit',  'Audit, legal, consultancy'),
  ('5350', 'Bank Charges',                       'expense',   'admin_expense',      'debit',  'Bank transaction and account fees'),
  ('5360', 'SMS and Email Costs',                'expense',   'admin_expense',      'debit',  'Notification provider charges'),
  ('5400', 'Marketing and Promotions',           'expense',   'admin_expense',      'debit',  'Member recruitment + brand spend'),
  ('5410', 'Training and Development',           'expense',   'staff_cost',         'debit',  'Staff training programmes'),
  ('5420', 'Insurance',                          'expense',   'admin_expense',      'debit',  'Asset and liability insurance premiums'),
  ('5500', 'Regulatory Fees',                    'expense',   'admin_expense',      'debit',  'SASRA, CMA levies'),
  ('5900', 'Other Operating Expenses',           'expense',   'admin_expense',      'debit',  'Sundry expenses')
) AS c(code, name, class, type, nb, descr);

-- Open the current month as the first accounting period for every
-- tenant — keeps the GL ready to receive entries from day one.
INSERT INTO accounting_periods (tenant_id, year, month, status, opened_at)
SELECT t.id, EXTRACT(YEAR  FROM now())::int,
              EXTRACT(MONTH FROM now())::int,
              'open', now()
FROM tenants t
ON CONFLICT DO NOTHING;
